theme: minima
default_lang: en
languages: ["en", "fr", "de"]
excerpt_separator: '<!-- more -->'
briefing_separator: '<!-- briefing-teacher -->'

permalink: /:lang/:title.html
title: Ranke.2 - Source Criticism in the Digital Age

exclude: [scripts/]
collections:
  units:
    output: true
    permalink: /u/:path/
  authors:
    output: true
    permalink: /a/:path/
  assignments:
    output: true
    permalink: /assignment/:slug/
