theme: minima
default_lang: en
languages: ["en", "fr", "de"]
excerpt_separator: '<!-- more -->'

permalink: /:lang/:title.html
title: RankeTwo

exclude: [scripts/]
collections:
  units:
    output: true
    permalink: /u/:path/
  authors:
    output: true
    permalink: /a/:path/