theme: minima
default_lang: en
languages: ['en', 'fr', 'de']
excerpt_separator: '<!-- more -->'
briefing_separator: '<!-- briefing-teacher -->'
section_separator: '<!-- section -->'
section_content_separator: '<!-- section-contents -->'
permalink: /:lang/:title.html
title: Ranke.2
headline: Source Criticism in the Digital Age
ranke2_baseurl: https://ranke2.uni.lu
exclude: [scripts/, d3/]
collections:
  units:
    output: true
    permalink: /u/:path/
  assignments:
    output: true
    permalink: /a/:path/
  workshops:
    output: true
    permalink: /w/:slug/
  tutorials:
    output: true
    permalink: /tutorial/:path/
defaults:
  - scope:
      path: ''
    values:
      layout: default

page_gen:
  - data: tags
    template: tag
    dir: tags
    name: id

markdown: kramdown
empty_array: []
recaptcha: 6LfZKnYUAAAAAJGg9r--abfv5A08TDORCmv4mGOx
google_analytics: UA-97728144-3
forms:
  contact-us:
    url: 'https://ranke2.uni.lu/ecf/'
    params:
      - name: use
        value: ranke2
plugins:
  - jekyll-datapage-generator
  - jekyll-github-metadata
