theme: minima
default_lang: en
languages: ["en", "fr", "de"]
excerpt_separator: '<!-- more -->'
briefing_separator: '<!-- briefing-teacher -->'
section_separator: '<!-- section -->'
section_content_separator: '<!-- section-contents -->'
permalink: /:lang/:title.html
title: Ranke.2
headline: Source Criticism in the Digital Age
exclude: [scripts/, d3/]
collections:
  units:
    output: true
    permalink: /u/:path/
  authors:
    output: true
    permalink: /a/:path/
  assignments:
    output: true
    permalink: /assignment/:slug/
markdown: kramdown
empty_array: []
