version: '3.7'
services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle:Z
    ports:
      - '${PORT:-4000}:4000'
      - '${POLLING_PORT:-35729}:35729'
    entrypoint: jekyll serve  --incremental --livereload --force_polling
    environment:
      FORCE_POLLING: 'true'
